src/Entity/Blogs.php
<?php

namespace App\Entity;

use App\Repository\BlogsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\User;

#[ORM\Entity(repositoryClass: BlogsRepository::class)]
class Blogs
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $picture = null;

    #[ORM\Column(length: 255)]
    private ?string $tags = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\ManyToOne(targetEntity: User::class)]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $author = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $slug = null;

    #[ORM\OneToMany(mappedBy: 'blog', targetEntity: Comment::class, orphanRemoval: true, cascade: ['persist'])]
    private Collection $comments;


    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): static
    {
        $this->picture = $picture;
        return $this;
    }

    public function getTags(): ?string
    {
        return $this->tags;
    }

    public function setTags(string $tags): static
    {
        $this->tags = $tags;
        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;
        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;
        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(User $author): static
    {
        $this->author = $author;
        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;
        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;
        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setBlog($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            if ($comment->getBlog() === $this) {
                $comment->setBlog(null);
            }
        }

        return $this;
    }

    public function getPicturePath(): string
    {
        return $this->picture;
    }
}

src/Entity/User.php
<?php
namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $firstName = null;

    #[ORM\Column(length: 100)]
    private ?string $lastName = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column(type: 'json')]
    private array $roles = ["ROLE_USER"];

    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column]
    private bool $isVerified = false;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $picture = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updatedAt = null;

    // === GETTERS & SETTERS ===

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;
        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): static
    {
        $this->lastName = $lastName;
        return $this;
    }

    public function getFullName(): string
    {
        return $this->firstName . ' ' . $this->lastName;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;
        return $this;
    }

    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';
        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;
        return $this;
    }

    public function hasRole(string $role): bool
    {
        return in_array($role, $this->getRoles(), true);
    }

    public function isAuthor(): bool
    {
        return $this->hasRole('ROLE_AUTHOR');
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;
        return $this;
    }

    public function eraseCredentials(): void
    {
        // vider les données sensibles temporaires ici si besoin
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;
        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): static
    {
        $this->picture = $picture;
        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    #[ORM\PrePersist]
    public function onPrePersist(): void
    {
        $now = new \DateTimeImmutable();
        $this->createdAt = $now;
        $this->updatedAt = $now;
    }

    #[ORM\PreUpdate]
    public function onPreUpdate(): void
    {
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getPicturePath(): string
    {
        return $this->picture 
            ? 'assets/images/blog/' . $this->picture 
            : 'assets/images/blog/default-user.png';
    }
}

src/Controller/BlogsController.php
<?php

namespace App\Controller;

use App\Entity\Blogs;
use App\Entity\Comment;
use App\Form\CommentFormType;
use App\Repository\BlogsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class BlogsController extends AbstractController
{
    #[Route('/blogs', name: 'blogs')]
    public function index(BlogsRepository $repository, PaginatorInterface $paginator, Request $request)
    {
        $query = $repository->findAllPaginatedQuery();

        $blogs = $paginator->paginate(
            $query,
            $request->query->getInt('page', 1),
            9
        );

        return $this->render('pages/blogs/blogs.html.twig', [
            'blogs' => $blogs,
        ]);
    }

    #[Route('/blog_sidebar', name: 'blog_sidebar')]
    public function blogSide(): Response
    {
        return $this->render('pages/blogs/blog-sidebar.html.twig', [
            'controller_name' => 'BlogsController',
        ]);
    }

    #[Route('/blog/{slug}', name: 'blog_details')]
    public function show(string $slug, Request $request, EntityManagerInterface $em): Response
    {
        $blog = $em->getRepository(Blogs::class)->findOneBy(['slug' => $slug]);

        if (!$blog) {
            throw $this->createNotFoundException('Blog not found');
        }

        $comment = new Comment();
        $comment->setBlog($blog);
        $comment->setCreatedAt(new \DateTimeImmutable());

        $form = $this->createForm(CommentFormType::class, $comment, [
            'user' => $this->getUser(),
        ]);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            if ($this->getUser()) {
                $comment->setUser($this->getUser());
            }

            $em->persist($comment);
            $em->flush();

            $this->addFlash('success', 'Commentaire ajouté avec succès !');
            return $this->redirectToRoute('blog_details', ['slug' => $slug]);
        }

        return $this->render('pages/blogs/blog-details.html.twig', [
            'blog' => $blog,
            'commentForm' => $form->createView(),
        ]);
    }
}

templates/partials/blog/_author_card.html.twig
{# templates/partials/blog/_author_card.html.twig #}
<div class="blog__writer">
	<div class="blog__writer-thumb">
		<img src="{{ asset(blog.author.picture) }}" alt="{{ blog.author.getFullName() }}">
	</div>
	<div class="blog__writer-designation">
		<p>{{ blog.author.getFullName() }}</p>
		<span>{{ blog.createdAt|date('d M Y') }}</span>
	</div>
</div>

templates/partials/blog/_card.html.twig
<div class="blog__item">
    <div class="blog__item-inner blog__item-inner--style2">
        <div class="blog__thumb">
            <img src="{{ asset(blog.picture) }}" alt="{{ blog.title }}">
        </div>
        <div class="blog__content">
            <div class="blog__meta">
                <span class="blog__meta-tag blog__meta-tag--style1">{{ blog.tags }}</span>
            </div>
            <h5 class="10 style2">
                <a href="{{ path('blog_details', { slug: blog.slug }) }}">{{ blog.title }}</a>
            </h5>
            <p class="mb-15">{{ blog.description|slice(0, 100) ~ '...' }}</p>
            <div class="blog__writer">
                <div class="blog__writer-thumb">
                    <img src="{{ asset(blog.author.picture) }}" alt="{{ blog.author.getFullName() }}">
                </div>
                <div class="blog__writer-designation">
                    <p>{{ blog.author.getFullName() }}</p>
                    <span>{{ blog.createdAt|date('d M Y') }}</span>
                </div>
            </div>
        </div>
    </div>
</div>

templates/partials/blog/_details_content.html.twig
<div
	class="blog-details__item-inner">

	{# Image principale #}
	{% if blog.picture %}
		<div class="blog-details__thumb">
			<div class="blog-details__thumb-inner" data-aos="fade-up" data-aos-duration="800">
				<img src="{{ asset(blog.picturePath) }}" alt="{{ blog.title }}">
			</div>
		</div>
	{% endif %}

	{# Contenu principal #}
	<div class="blog-details__content">
		<h3>{{ blog.title }}</h3>

		<div class="blog-details__meta">
			<ul>
				<li>
					<img src="{{ asset('assets/images/blog/icon/1.png') }}" alt="author">
					{{ blog.author ? blog.author.getFullName() : 'Unknown Author' }}
				</li>
				<li>
					<img src="{{ asset('assets/images/blog/icon/2.png') }}" alt="date">
					{{ blog.createdAt|date('F j, Y') }}
				</li>
				<li>
					<img src="{{ asset('assets/images/blog/icon/3.png') }}" alt="comments">
					{{ blog.comments|length }}
					Comment{{ blog.comments|length > 1 ? 's' : '' }}
				</li>
			</ul>
		</div>

		<p class="mb-0">{{ blog.description|nl2br }}</p>
	</div>

	<div class="blog-details__content-bottom mt-4" data-aos="fade-up" data-aos-duration="1000">
		<div
			class="blog-details__action-inner d-flex justify-content-between align-items-center flex-wrap border-top border-bottom py-3">

			{# TAGS #}
			<div class="blog-details__tag">
				<div class="tags tags--style2 d-flex align-items-center gap-2">
					<h6 class="mb-0 me-2">Tags:</h6>
					<ul class="d-flex flex-wrap gap-2 mb-0 ps-0">
						{% for tag in blog.tags|split(',') %}
							<li>
								<a href="#" class="active">{{ tag|trim }}</a>
							</li>
						{% endfor %}
					</ul>
				</div>
			</div>

			{# SOCIAL SHARE #}
			<div class="blog-details__social">
				<ul class="social d-flex align-items-center gap-2 mb-0">
					<li>
						<h6 class="mb-0 me-2">Share:</h6>
					</li>
					<li>
						<a href="#" class="social__link social__link--style2 active">
							<i class="fab fa-facebook-f"></i>
						</a>
					</li>
					<li>
						<a href="#" class="social__link social__link--style2">
							<i class="fab fa-instagram"></i>
						</a>
					</li>
					<li>
						<a href="#" class="social__link social__link--style2">
							<i class="fab fa-linkedin-in"></i>
						</a>
					</li>
					<li>
						<a href="#" class="social__link social__link--style2">
							<i class="fab fa-youtube"></i>
						</a>
					</li>
				</ul>
			</div>
		</div>
	</div>


	{# Commentaires #}
	<div class="blog-details__comment mt-5">
		<h3>{{ blog.comments|length }}
			Comment{{ blog.comments|length > 1 ? 's' : '' }}</h3>
		<ul>
			{% for comment in blog.comments %}
				<li class="sidebar__comment-item">
					<div class="comment">
						<div class="comment__inner">
							<div class="comment__head">
								<div class="comment__author">
									<div class="comment__author-thumb">
										<img src="{{ asset(comment.user ? comment.user.getPicture : 'assets/images/blog/default-user.png') }}" alt="author" class="rounded-circle" width="40" height="40">
									</div>
									<div class="comment__author-info">
										<h6 class="mb-0">
											{{ comment.user ? comment.user.fullName : comment.authorName }}
										</h6>
										<span>{{ comment.createdAt|date('F j, Y H:i') }}</span>
									</div>
								</div>
							</div>
							<div class="comment__body">
								<div class="comment__body-inner">
									<p class="mb-0">{{ comment.content|nl2br }}</p>
								</div>
							</div>
						</div>
					</div>
				</li>
			{% else %}
				<li>
					<p>No comments yet.</p>
				</li>
			{% endfor %}
		</ul>
	</div>

	{# Formulaire #}
	<div class="sidebar__commentform-body pt-25">
		{{ form_start(commentForm) }}
		<div class="row g-4">
			{% if not app.user %}
				<div class="col-md-6">
					{{ form_row(commentForm.authorName) }}
				</div>
				<div class="col-md-6">
					{{ form_row(commentForm.email) }}
				</div>
			{% else %}
				<div class="col-md-12 d-flex align-items-center gap-3 mb-3 bg-light p-3 rounded">
					<img src="{{ asset(app.user.getPicture) }}" alt="user" class="rounded-circle" width="40" height="40">
					<div>
						<strong class="text-dark">{{ app.user.fullName }}</strong><br>
						<small class="text-muted">{{ app.user.email }}</small>
					</div>
				</div>
			{% endif %}

			<div class="col-md-12">
				{{ form_row(commentForm.content) }}
			</div>

			<div class="col-md-12">
				<button type="submit" class="trk-btn trk-btn--border trk-btn--primary mt-4">Send message</button>
			</div>
		</div>
		{{ form_end(commentForm) }}
	</div>

</div>

templates/partials/blog/_sidebar.html.twig
{# templates/partials/blog/_sidebar.html.twig #}
<div class="sidebar">
	<div class="sidebar__search mb-4">
		<h6>Search Here</h6>
		<form action="#">
			<div class="input">
				<input type="text" class="form-control" placeholder="Search articles">
				<button type="submit" class="search-btn">
					<i class="fa-solid fa-magnifying-glass"></i>
				</button>
			</div>
		</form>
	</div>

	<div class="sidebar__categorie mb-4">
		<h6>Categories</h6>
		<ul>
			<li>
				<a href="#">Large-cap stocks</a>
				<span>2</span>
			</li>
			<li>
				<a href="#">Value stocks</a>
				<span>4</span>
			</li>
			<li>
				<a href="#">IPO stocks</a>
				<span>3</span>
			</li>
			<li>
				<a href="#">Dividend stocks</a>
				<span>5</span>
			</li>
			<li>
				<a href="#">Non-dividend stocks</a>
				<span>1</span>
			</li>
		</ul>
	</div>

	<div class="sidebar__recentpost mb-4" data-aos="fade-up" data-aos-duration="1000">
		<div class="sidebar__head">
			<h6>Recent Posts</h6>
		</div>
		<div class="sidebar__recentpost-body">
			<ul>
				<li>
					<div class="sidebar__recentpost-item">
						<div class="sidebar__recentpost-inner">
							<div class="sidebar__recentpost-thumb">
								<a href="#"><img src="{{ asset('assets/images/blog/recent/1.png') }}" alt="recent"></a>
							</div>
							<div class="sidebar__recentpost-content">
								<p>
									<a href="#">Real Estate Investing</a>
								</p>
								<span>Dec 22, 2023</span>
							</div>
						</div>
					</div>
				</li>
				<li>
					<div class="sidebar__recentpost-item">
						<div class="sidebar__recentpost-inner">
							<div class="sidebar__recentpost-thumb">
								<a href="#"><img src="{{ asset('assets/images/blog/recent/2.png') }}" alt="recent"></a>
							</div>
							<div class="sidebar__recentpost-content">
								<p>
									<a href="#">Technical analysis</a>
								</p>
								<span>July 28, 2023</span>
							</div>
						</div>
					</div>
				</li>
				<li>
					<div class="sidebar__recentpost-item">
						<div class="sidebar__recentpost-inner">
							<div class="sidebar__recentpost-thumb">
								<a href="#"><img src="{{ asset('assets/images/blog/recent/3.png') }}" alt="recent"></a>
							</div>
							<div class="sidebar__recentpost-content">
								<p>
									<a href="#">Trading risk tolerance</a>
								</p>
								<span>May 18, 2023</span>
							</div>
						</div>
					</div>
				</li>
				<li>
					<div class="sidebar__recentpost-item">
						<div class="sidebar__recentpost-inner">
							<div class="sidebar__recentpost-thumb">
								<a href="#"><img src="{{ asset('assets/images/blog/recent/4.png') }}" alt="recent"></a>
							</div>
							<div class="sidebar__recentpost-content">
								<p>
									<a href="#">Harmonic price pattern</a>
								</p>
								<span>Feb 16, 2023</span>
							</div>
						</div>
					</div>
				</li>
			</ul>
		</div>
	</div>


	<div class="sidebar__tags">
		<h6>Popular Tags</h6>
		<ul class="tags tags--style2">
			<li>
				<a href="#" class="active">Analysis</a>
			</li>
			<li>
				<a href="#">Research</a>
			</li>
			<li>
				<a href="#">Mentoring</a>
			</li>
			<li>
				<a href="#">Strategy</a>
			</li>
			<li>
				<a href="#">Planning</a>
			</li>
			<li>
				<a href="#">Business</a>
			</li>
			<li>
				<a href="#">Leadership</a>
			</li>
			<li>
				<a href="#">Management</a>
			</li>
		</ul>
	</div>
</div>